### ISSUE TITLE
Tests are not efficient and take too long to run

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Standard-Website#224]
Current tests are not in an ideal state due to trade-offs made against time constraints that did not allow for enough research, planning, and experimentation before development.

Ideally, they need rewriting in favour of unit tests in many cases, removing the resource burden and time inefficiency of selenium testing where it isn't necessary. This is especially true of much of the model testing.

Places where selenium testing would be beneficial do not necessarily require manoeuvring around the CMS and could be instead performed against a site generated with test data dumped into the test database.

Duplicate functional tests need to be consolidated or removed. Some tests even now do not require admin access to the CMS.

**Comment by samuele-mattiuzzo** [comment]
Bringing this one back to life, as we now have master failing due to Selenium tests timing Travis out

```
October 26, 2018 - 14:27:11
Django version 2.0.5, using settings 'iati.settings.dev'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
EEEEEEEEEEEEEE
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by sargentfrancesca** [comment]
Starting investigation on this now. My initial thoughts are that the majority of the tests are actually testing default Django/Wagtail behaviour, and therefore do not need to be replicated, and there isn't custom behaviour added to the build, aside from redirects and middleware. There are tests that could be useful to keep.

**Comment by sargentfrancesca** [comment]
## `about_functional_tests.py`

### `TestAboutPage`

* `test_can_edit_about_page_heading`: tests core functionality
* `test_can_edit_about_page_excerpt`: tests core functionality
* `test_can_edit_about_page_with_header_text`: tests core functionality


### `TestAboutChildPages`

* `test_can_create_about_child_pages`: tests core functionality
* `test_can_edit_about_child_page_heading`: tests core functionality
* `test_can_edit_about_child_page_excerpt`: tests core functionality
* `test_can_edit_about_child_page_with_header_text`: tests core functionality

### `TestCaseStudyPage`

* `test_no_case_studies_section_on_home`: tests template and model method
* `test_can_create_case_study_page`: tests core functionality
* `test_case_studies_section_on_home`: tests template and model method
* `test_can_edit_case_study_page_heading`: tests core functionality
* `test_can_edit_case_study_page_excerpt`: tests core functionality
* `test_can_edit_case_study_page_with_header_text`: tests core functionality
* `test_feed_image_shows_on_index_page`: tests template
* `test_feed_image_shows_in_page_header`: tests template


## `base_functional_tests.py`

### `TestCreateDefaultPagesManagementCommand`

* `test_create_default_pages_idempotence`: tests a management command

### `TestDefaultPages`

* `test_default_pages_exist`: tests core functionality
* `test_header_image_is_editable`: tests core functionality

### `TestTopMenu`

* `test_top_menu`: tests core functionality

### `StreamFieldFiller`

* no tests

## `contact_functional_tests.py`

empty

## `events_functional_tests.py`

### `TestEventIndexPage`

* `test_can_edit_event_page_heading`: tests core functionality
* `test_events_past_parameter`: tests template and model method
* `test_can_edit_event_page_excerpt`: tests core functionality

### `TestEventPages`

* `test_can_create_event_child_pages`: tests core functionality
* `test_can_edit_event_child_page_heading`: tests core functionality
* `test_can_edit_event_child_page_excerpt`: tests core functionality
* `test_can_edit_event_child_page_with_header_text`: tests core functionality
* `test_event_type_filter`: tests core functionality
* `test_feed_image_shows_on_index_page`: tests template and model method
* `test_feed_image_shows_in_page_header`: tests template and model method

### `TestFeaturedEvents`

* `test_featured_event`: tests template and model method


## `functional_tests.py`

### `TestHomePageExists`

* `test_home_page_has_IATI_logo`: tests template and model method
*  `test_home_page_logo_is_a_home_link`: tests template and model method

## `guidance_unit_tests.py`

* `test_generate_ticket`: tests Zendesk

## `home_functional_tests.py`

### `TestHomePage`

* `test_can_edit_home_page_heading`: tests core functionality 
* `test_can_edit_home_page_excerpt`: tests core functionality 


### `TestFixedStandardPages`

* `test_can_create_standard_pages`: tests template and model method

## `iati_standard_functional_tests.py`

### `TestIATIStandardPageisEditable`

* `test_header_can_be_edited`: tests core functionality
* `test_excerpt_can_be_edited`: tests core functionality 
* `test_body_content_can_be_edited_simple`: tests core functionality  

## `management_unit_tests.py`

*NB: seems to test component helper functions*

* `test_update_statistics`: tests management command
* `test_update_statistics_error`: tests management command
* `test_clean_dashes`: tests management command
* `test_clean_whitespaces`: tests management command

## `news_functional_tests.py`

### `TestNewsPage`

* `test_can_edit_news_page_heading`: tests core functionality
* `test_can_edit_news_page_excerpt`: tests core functionality

### `TestNewsIndexChildPages`

* `test_can_create_news_child_pages`: tests core functionality
* `test_can_edit_news_child_page_heading`: tests core functionality
* `test_can_edit_news_child_page_with_header_text`: tests core functionality
* `test_news_category_filter`: tests core functionality

## `redirects_unit_tests.py`

### `TestRedirectLinksWorking`

* `test_basic_redirects_work`: tests redirects using client
* `test_descendent_redirects_work`: tests redirects using client

## `support_functional_tests.py`

empty

## `using_data_functional_tests.py`

### `TestUsingDataPage`

* `test_can_edit_using_data_page_heading`: tests core functionality 
* `test_can_edit_using_data_page_excerpt`: tests core functionality 

### `TestUsingDataChildPage`

* `test_can_create_using_data_child_pages`: tests core functionality 
* `test_can_edit_using_data_child_page_heading`: tests core functionality 
* `test_can_edit_using_data_child_page_excerpt`: tests core functionality 


## Conclusion

* The majority of the tests are duplicating efforts of Wagtail core tests, and therefore do not need to be repeated. Due to the fact that there aren't any bespoke amendments to the CMS itself, it does not require testing in this way. They can be removed.

* We can remove selenium.

* Tests to ensure that entered data appears in pages are valid, as the template and/or model methods are being tested, however they depend on selenium. Worth looking at what the `client` will return instead, though my initial feeling is that we can assert what appears in the context, but not the template. I'll look into that more. I'm aware that [IATI-Website-Tests](https://github.com/IATI/IATI-Website-Tests/blob/master/tests/test_iati_standard.py) can fulfil this.

* Tests for the management commands are also valid, and need to be added widely, though I propose to use `call_command` to test the command as a whole, instead of testing its constituent functions.

* It is imperative to continue to test redirects.

* Fixtures are called throughout the code, and can cause tests to run slowly. I believe that using factories to replace this will be beneficial, we can investigate [wagtail-factories](https://github.com/mvantellingen/wagtail-factories).

**Comment by sargentfrancesca** [comment]
## To test (TBC)

### Redirects

* lowercase middleware #300 (_To Do_: find out more about when/how lowercase slugs were implemented)
* redirects to reference site
* redirects to reference site relative paths

### Management commands

* `createdefaultpages`
* `importnews`
* `replacelinks`
* `updatestatistics`


### Translations

* Investigation needed for this, but needs to be tested

### Models

* template/model logic, for example when checking case studies on the `HomePage`, client can investigate the context for `case_studies`
