### ISSUE TITLE
Add tests for lowercase middleware functionality

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/IATI-Standard-Website#300]
Currently #294 #295 are blocked pending addition of suitable tests.

This requires a separate issue to aid clarity around the discussion of implementing these tests, as this work runs alongside an overhaul of the tests (#224) ready for dockerising the build (#297), but will be deployed beforehand. The intention is to write tests according to how we plan to write them in the future, so although this temporarily adds _more_ dependencies, it'll prevent this work being duplicated needlessly. 

---

## Implement unit tests with mock data to test the redirects

*  Create a new file to isolate these tests from the others. 
*  Use `pytest` and assess its suitability. Selenium is not required for this.
*  Use Django sessions to log a super user in, negating the need to add them to the database
*  Use `FactoryBoy` to mock data, using [ImageField](https://factoryboy.readthedocs.io/en/latest/orms.html#factory.django.ImageField) and [FileField](https://factoryboy.readthedocs.io/en/latest/orms.html#factory.django.FileField) in a `factories.py` file, which `tests.py` can import from. See further information below for directions.

### Checklist of tests
* [x] uppercase slugs are redirected to lowercase slugs
* [ ] `/media/` slugs are _not_ redirected to lowercase slugs
* [x] `/document/` slugs are _not_ redirected to lowercase slugs
* [x] external redirects are _not_ redirected to lowercase slugs
* [ ] `/cms/` slugs are _not_ redirected to lowercase slugs
* [x] `/static/` slugs are not redirected to lowercase slugs (dependent on completion of [this PR comment](https://github.com/IATI/IATI-Standard-Website/pull/295#issuecomment-468269422)

#### Adding a Document and Image

The factory for a document can look something like this:

```
import factory
import factory.django

from wagtail.documents.models import Document


class DocumentFactory(factory.django.DjangoModelFactory):
    title = factory.Sequence(lambda n: f"document {n}")
    file = factory.django.FileField(filename="DoCumEntWithMixedCASE.txt", data=b'Test document')

    class Meta:
        model = Document
```

A function within the tests can create the Document

```
def create_document(self):
        return DocumentFactory.create()
```

Similarly, an image can be created too, using the `ImageField`.

#### Authenticating the User

It is possible to log in a user without relying on the database. `pytest-django` allows a user object to be created and authenticated - [see here](https://pytest-django.readthedocs.io/en/latest/helpers.html#id1), also see `admin_user`.

**Comment by Ocre42** [comment]
Whilst testing some basic cases I found out that there's some issues with the way the middlewares are routing things. From my tests I noticed that if the lowercase middleware is applied, it does not apply the language prefix define in `iati/activate_languages.py`, which might be caused by the way we return the responses in `custom_middleware.py`

**Comment by Ocre42** [comment]
On to the next couple of issues, starting with documents.
I can obtain the document url after defining it with the factory:
```
document = self.create_document()
response = client.get(document.url)
```
The issue is that response is an instance of `StreamingHttpResponse` and I can't seem to be able to find the url for the response, which should be the same as `documents/1/MiXeDcAsE.txt`, the closest thing I've gotten from running a dir on the response object has been `wsgi_request` which gives me `/documents/1/MiXeDcAsE_2XUyZdU.txt`, but even then it is a request and not the response url, so that is my current block on the document tests.

The image tests goes even deeper:
```
image = self.create_image()
response = client.get(image.url)
```
Here image is an instance of Image created via `ImageFactory`, it doesn't have an `url` but does have an `usage_url` which points to `/cms/images/usage/1/` and not to `/media/images/`, so I'll have to go a bit in depth as to how wagtail saves stuff into the media directory.

**Comment by Ocre42** [comment]
I've updated the document middleware to check for the status code to ensure that after doing the request we still get 200, and the factory will now generate a random file (with uppercases).

As for the locales, the middleware triggers before the urls are changed and looking at the `urls.py` it seems that it's supposed to be triggered for any urls that are not part of the first subset of url patterns:
```
urlpatterns = [  # pylint: disable=invalid-name
    url(r'^django-{}/'.format(settings.ADMIN_SLUG), admin.site.urls),
    url(r'^{}/'.format(settings.ADMIN_SLUG), include(wagtailadmin_urls)),
    url(r'^{}/'.format(settings.DOCUMENTS_SLUG), include(wagtaildocs_urls)),
]
```
Since my test urls for the cms don't exist in `wagtailadmin_urls` I'll have to work around this, perhaps create a fake temp wagtailadmin page with a mixedcase slug.
As for the `/Home/` -> `/home/` -> `/en/home/`, adding the `follow=True` flag raises a redirect loop error, and HttpResponsePermanentRedirect objects have no redirect_chain attribute associated.
