### ISSUE TITLE
Unable to find developer page from main site

### ISSUE THREAD

**Issue by rossjones** [IATI/IATI-Standard-Website#362]
**Describe the bug**

Whilst browing https://iatistandard.org/en/ I was unable to find a link to http://reference.iatistandard.org/203/developer/ and this was frustrating. Eventually relied on Google to find it at http://reference.iatistandard.org/203/developer/

**To Reproduce**

1. Visit https://iatistandard.org/en/ 
2. Click on https://iatistandard.org/en/iati-community/ 
3. Look confused
4. Visit https://discuss.iatistandard.org/ (and accidentally notice not everything is loaded over https :( ).
5. Look for the 'I want to contribute section'
6. Give up, go to google.
7. FInd the page, read the docs.

**Expected behavior**

On visiting https://iatistandard.org/en/iati-community/ to see a section (underneath Discuss) called Contribute, linking to http://reference.iatistandard.org/203/developer/

**Comment by samuele-mattiuzzo** [comment]
Hi Ross, we'll look into that asap, although I can tell you a couple of sneak-peak things:

- we are reworking the information architecture of the main website because, as you unfortunately experienced yourself, it isn't easy nor quick "3-clicks" way of finding the information one needs

- the reference site will be brought into the main website as part of that rework

hopefully that sort of explains it a bit (although yes, it doesn't solve the problem)

**Comment by samuele-mattiuzzo** [comment]
FWIW, the steps would be:

- visit https://iatistandard.org/en/
- click on IATI STANDARD, to be taken here https://iatistandard.org/en/iati-standard/
- scroll to the bottom, bottom-right box, click `Informations for Developers`

**Comment by samuele-mattiuzzo** [comment]
Website's navigation and AI is being reworked, closing this
