### ISSUE TITLE
Build the content of the reference pages using the SSOT

### ISSUE THREAD

**Issue by Ocre42** [IATI/IATI-Standard-Website#384]
Adapt the code available in the [IATI-Standard-SSOT Repository]( https://github.com/IATI/IATI-Standard-SSOT) so it can be used to populate the new reference templates for the IATI Standard Website

**Comment by urlsangel** [comment]
### Static code examples in the pattern library

#### PL Template

There is a new template in the pattern library which contains at least one piece of example markup which utilises the CSS class selectors listed in the output of @akmiller01's script.

- **PL Template (front end):** http://iati.surge.sh/page-templates/09-1d-example-content
- **PL Template (source code):** https://github.com/IATI/IATI-Standard-Website/blob/feature/reference-data/patterns/templates/page-templates/09-1d-example-content.html
- **Class list:** https://github.com/IATI/IATI-Standard-Website/blob/feature/reference-data/patterns/ssot/ssot-class-list.json

#### HMTL includes

The PL template example content is made up of these of html includes:

- **Template includes:** https://github.com/IATI/IATI-Standard-Website/tree/feature/reference-data/patterns/includes/ssot
- **Example include:** https://github.com/IATI/IATI-Standard-Website/blob/feature/reference-data/patterns/includes/ssot/div.code.highlight-default.html

Each HTML include contains a snippet of HTML that utilises one or more of the classes. This HTML snippet has had all classes removed whilst maintaining the structure (with one exception - see below), whilst the original snippet - including all classes - is in a commented-out section below for reference.

#### In situ links and include references

The value of each unique CSS selector in the  [class list](https://github.com/IATI/IATI-Standard-Website/blob/feature/reference-data/patterns/ssot/ssot-class-list.json) is a link to the first page that contains that class in situ, and each value has a comment next to it which refers to the PL HTML include that contains example markup.

#### Altered structure

The structure of the HTML includes has been amended in one specific case:

- **Where markup is of the form:** `<code class="docutils literal"><span class="pre">[some content]</span></code>`
- **This has been altered to:** `<code><pre>[some content]</pre></code>`

#### Code highlighting spans

There are a number of one or two letter CSS `span` selectors that appear to be used for code highlighting.

The classes have been removed from these spans, but I think it would make sense if we removed the associated `span` markup as well, as code highlighting will be implemented via JavaScript, and leaving them in the markup is likely to be problematic.

#### Some classes might need to remain

There are a few edge cases where removing the class leaves a structure that can no longer be styled, as the markup is not semantic enough to add selectors to.

In some cases, markup could be amended to swap out a class with a piece of semantic markup.

Examples (this is not a definitive list):

- **`div.line-block` / `div.line`:** these classes appear in nested divs that act just like paragraphs. Without these classes the contained text does not have the correct font size or margin as a regular `p` tag. **Example:** see what appears to be the [second paragraph here, starting with "The IATI activity standard is the..."](http://iati.surge.sh/page-templates/09-1d-example-content#definition)
- **`span.underline`:** this class appears in inline text, and emphasises words with an underline. **Example:**  [See the words "original" and "revised" in the "budget" section of this text](http://reference.iatistandard.org/203/activity-standard/overview/budgets/#definition)
- **`tr.withdrawn.row-even`:** this class causes the `tr` child text to be a lighter colour and italic. **Example:**  [See "Netherland Antilles" row in the "Codes" table here](http://reference.iatistandard.org/203/codelists/Country/#codes)

### Next steps

The example markup in the PL template should be reviewed, with classes amended or suggestions given of how to retain the information contained in the current set of styles (e.g. don't delete certain classes, refactor the markup etc.)

Once this task is complete and suggestions given, the HTML transformation script should be updated so that the Beautiful Soup processes the static HTML to the right format.

This can then be reviewed by Amy to check if the process results in correctly styled HTML content.

#### Previous versions of the standard

The above task has only be done on the latest version of the standard 2.0.3. It is advisable that the previous versions are checked for any styles that have not been captured by the task so far, so that we can determine if they also require classes whitelisting or styling.

**Comment by BenDarby** [comment]
I've started going through the outputted HTML includes to make notes and change the markup to make it more semantic where needed. I've made a few observations and changes as follows: 

First thing I created a modifier class of `is-typeset--data` so we can style anything specific to this outputted HTML 

- `div.line-block` / `div.line`: This isn't great as they should be `p` tags, I can style `div` to act as `p` but it's not very semantic, my suggestion if possible is to remove the `div.line-block` and change the `div.line` to be `p`
- `span.underline`: this seems to act as an emphasis tag from what I can tell, my suggestion would be to replace this with an `em` and style it so it looks the same still, also then we'll have a consistent style for all `em` which would be better too
- `div.highlight`:  this class is used for code highlighting but we have something in place for this with the `code` tag. My suggestion would be to remove this `div` and replace it with `code`. Also, we can strip out the span within this as they don't seem to be adding anything style-wise.

These are just a few items I've noticed while going through and updating the template on surge. I have made these edits on the PL already so you can see what it's like: http://iati.surge.sh/page-templates/09-1d-example-content

**Comment by benjamincoleman** [comment]
@BenDarby One issue I've seen here which we introduced is caused by this CSS: 

```
.is-typeset pre code {
    display: block;
    overflow-x: auto;
    white-space: pre-wrap;
    word-wrap: break-word;
}
```

The display block is causing problems as you can see here, where the code blocks should appear inline as part of the text: 

![Screenshot 2020-04-01 at 14 43 32](https://user-images.githubusercontent.com/64877/78144219-3a5de500-7427-11ea-99b1-0cd6055ac277.png)

**Comment by akmiller01** [comment]
Thoughts on storing these transformations as JSON for ease of maintenance? Working on something like:
```
[
  {
    "old_tag": "span",
    "old_class": "pre",
    "new_tag": "pre",
    "new_class": ""
  },
  {
    "old_tag": "div",
    "old_class": "line-block",
    "new_tag": "p",
    "new_class": ""
  },
  {
    "old_tag": "div",
    "old_class": "line",
    "new_tag": "p",
    "new_class": ""
  },
  {
    "old_tag": "span",
    "old_class": "underline",
    "new_tag": "em",
    "new_class": ""
  },
  {
    "old_tag": "div",
    "old_class": "highlight",
    "new_tag": "code",
    "new_class": ""
  },
]
```

Which I could loop through in Python.

**Comment by urlsangel** [comment]
Hi @akmiller01 

As discussed, here's a natural language algorithm, of what we need to transform ([based on Ben's comments here](https://github.com/IATI/IATI-Standard-Website/issues/384#issuecomment-607250813)):

```
If `div.line-block` has single child of `div.line`:
    Remove/unwrap outer `div.line-block`

If element == `div.line`:
    Remove class, convert element to `p`

# this rule is subject to approval by Amy
If element == `span.underline`:
    Remove class, convert element to `em`

If element == `span.caption-text`:
    Remove class, convert element to `caption`

If element == `tr.withdrawn`:
    Leave element and class in place

If element == `code` and has child or children `span.pre`:
    Remove `code` class, remove/unwrap `span` child, leave `span` text contents 

If element == `div.code.highlight-default` and has child or children `div.highlight`:
    Remove/unwrap `div.code.highlight-default`, convert `div.highlight` children to `code elements and remove class
```

Apart from these cases, all other classes can be removed, and the markup structure left as is.

**Comment by akmiller01** [comment]
Cheers @urlsangel . I'm not sure if this is exactly intuitive, but I've broken my transformation JSON into two steps based on the above, first, unwrap, and then, transform:

https://github.com/akmiller01/IATI-Reference-Generator/blob/master/class_transformations.json
