### ISSUE TITLE
T8.3 Tools & Resources

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#390]
Sketch: https://marvelapp.com/4cfjg52/screen/60422957

Design: http://iati.surge.sh/page-templates/08-3-tools-resources

Original issue and comments: https://github.com/IATI/IATI-Pattern-Library/issues/115

This is the header page for this section. 

**Hero**

- Title
- Intro
- Background image

**Left nav** 
shows pages in this section. There are sub pages of tools that need to show when you are looking at the tool. 

**Content**

Content editor for content at the top of the main content area. 

Tools are listed to show their purpose / what they enable people to do. 

For each tool we have: 

- Tool logo
- Title
- Description of what this tool does
- Link to the internal page about this tool
- Link to the external URL of the tool 

The AIMS integration piece has been added as a box, I think this is really important for an engagement perspective, so this appears as the last box. The AIMS box would consist of: 

- Title
- Content Editor

**Comment by urlsangel** [comment]
@benjamincoleman 

For the tool listing, the above description states:

> For each tool we have:
> 
> - Tool logo
> - Title
> - Description of what this tool does
> - Link to the internal page about this tool
> - Link to the external URL of the tool

It looks to me like the data for all of these fields is available from the individual pages themselves, however, the description of "d-portal" is different in the listing and single templates:

- http://iati.surge.sh/page-templates/08-3-tools-resources
- http://iati.surge.sh/page-templates/08-4-tool

So, should the data be taken just from the pages? In that case we don't need to allow content management on the listing page, as the order can come from the Wagtail child page sort order.

If a field such as description should be different on the listing page rather than the single page, then we could use a repeater to select pages and allow overrides (not sure if this would be good for translation though).

Be good to hear your thoughts.

**Comment by benjamincoleman** [comment]
The content in each of these places is different, and different deliberately. 

So, for the hero content we need one field, and then also an `excerpt` for the listing.

Then I'd say a repeater to allow them to control the order?
