### ISSUE TITLE
Meganav

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#391]
Sketch: https://marvelapp.com/4cfjg52/screen/60425986

Designs in any page of the PL: http://iati.surge.sh/page-templates/06-1-guidance-page

Original issue here: https://github.com/IATI/IATI-Pattern-Library/issues/120

---

Want to make this Accessible - https://github.com/IATI/IATI-Pattern-Library/issues/125

And then implement on the website. 

We'll need an updated version for the current state of development - we won't have a "Get Involved" section yet, but that will still be "Community". The content would be as you can see in this sketch: https://marvelapp.com/4cfjg52/screen/64550379

**Comment by urlsangel** [comment]
@Ben C 

Just wanted to note my thinking in this issue.

[This article about accessible meganavs on Smashing](https://www.smashingmagazine.com/2017/11/building-accessible-menu-systems/) is very good, and the conclusion I draw is that you can't fully do this without JS.

With that in mind, I'm planning to use [this library](https://github.com/AllThingsSmitty/accessible-mega-menu), as it implements everything well. It's not been updated for a while, but that's likely because the issue is solved and there's no need for updates.

Give me a shout if you have any concerns.

**Comment by benjamincoleman** [comment]
Yep, I knew about the JS thing, this is fine

**Comment by benjamincoleman** [comment]
<img width="1179" alt="Screenshot 2020-03-12 at 15 59 06" src="https://user-images.githubusercontent.com/64877/76541028-daed6480-647a-11ea-8e4e-0b61bd83bdf3.png">


Modules like “Finances, Reports and Minutes” should be able to have titles that are links, as well as just plain titles.

Here’s what we currently have, so @Ben Darby can you make “Finances, Reports and Minutes” title a link please?

**Comment by BenDarby** [comment]
@benjamincoleman the ability to have headings as links have been setup already so just update the model and all good now :)

**Comment by urlsangel** [comment]
@BenDarby 

Good spot, I'll update the PL as it needs to reflect what I've done in production 👍

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

I've updated the PL, and pushed latest to surge - you can now see this variant under the 'Governance' primary menu item:

http://iati.surge.sh/page-templates/0-home
