### ISSUE TITLE
Update meganav list style

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#481]
Longer explanation worth reading here: https://docs.google.com/document/d/1p3IN5NphXYtaCu_jw6i9YBYnacyUVZxqe8pTQjyIeEI/edit

Remove the vertical blue lines from the design and make sure all text is in a white box. 

So this: 

![Screenshot 2020-04-16 at 15 41 34](https://user-images.githubusercontent.com/64877/79469995-c7449900-7ff8-11ea-9180-4fb5fb324b2d.png)

Should have the line removed and it should be ina white box like the other menu elements: 

![Screenshot 2020-04-16 at 15 42 14](https://user-images.githubusercontent.com/64877/79470056-dcb9c300-7ff8-11ea-92be-0ecb51b4ae22.png)

**Comment by BenDarby** [comment]
@benjamincoleman I've updated surge so you can see that all the meganav items are in the white boxes and the blue left border is gone. It looked like they were combining multiple classes rather than either-or. 
We basically remove the `navigation-megamenu__col--border` modifier class and have the megamenu items contained withing the `m-highlight div `
It's on surge as well http://iati.surge.sh/page-templates/

**Comment by urlsangel** [comment]
@BenDarby 

There's a lone list on the right hand side without the new white background under **Tools and Resources** - I'm guessing this should be the same as the rest, and this style shouldn't exist anymore, right?

http://iati.surge.sh/page-templates/0-home

![Screenshot 2020-04-20 at 10 17 29](https://user-images.githubusercontent.com/560463/79735734-a1690e00-82f0-11ea-806b-4d89ccdd1189.png)

**Comment by BenDarby** [comment]
@urlsangel yeah it should have the white background. I missed it in model, sorry

**Comment by urlsangel** [comment]
@BenDarby - no worries, I'll fix it up :-)

**Comment by urlsangel** [comment]
@BenDarby 

That's updated now in the bracnh and on surge:

**Comment by BenDarby** [comment]
@urlsangel pushed a fix, removed padding top as it's not needed anymore
