### ISSUE TITLE
Adding more elements to SSOT content

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#486]
We've found more elements to be styled in the SSOT content: 

- blockquote
- colgroup
- col 
- caption 
- dl 
- dt 
- dd 
- cite

you can see some examples of these by checking out this doc: https://docs.google.com/document/d/1T7QuxhAdu1XhoA4vq7rE1WpsJXxqCs-lMPGNv7iRXRA/edit#

**Comment by BenDarby** [comment]
@benjamincoleman I pushed some styling fixes for

- caption
- dl
- dt
- dd

I updated the sheet with notes about 

- colgroup
- col

And apart from blockquotes in tables where they shouldn't be blockquotes I couldn't find other issues? Will the markup outputted change so blockquotes are not used in a table? Otherwise, I can amend some styles, it just won't be semantic

**Comment by benjamincoleman** [comment]
Hi Ben, 

The Blockquotes in tables were really broken code blocks, so no need to worry about them. 

I'll review today and see where we are. 

B

**Comment by benjamincoleman** [comment]
Some updates on this: 

https://docs.google.com/document/d/1T7QuxhAdu1XhoA4vq7rE1WpsJXxqCs-lMPGNv7iRXRA/edit#bookmark=id.jejd12h550nq

https://docs.google.com/document/d/1T7QuxhAdu1XhoA4vq7rE1WpsJXxqCs-lMPGNv7iRXRA/edit#bookmark=id.n6vnsq57anp

**Comment by BenDarby** [comment]
@benjamincoleman I addressed this issues, pushed and updated the status sheet.

**Comment by benjamincoleman** [comment]
@BenDarby are these elements now visible in a pattern library template?

**Comment by benjamincoleman** [comment]
@urlsangel I think Ben has done all he can to style elements. I've updated the google doc, and think this is good to deploy.
